// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDoGstM2rQaEB0fl4Qfzh0OCVtuNs3Uuh8',
    appId: '1:290159247030:web:a741ce01dcdbea439a3017',
    messagingSenderId: '290159247030',
    projectId: 'fruitmobile-31368',
    authDomain: 'fruitmobile-31368.firebaseapp.com',
    storageBucket: 'fruitmobile-31368.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYKRsLY-ko3kGGUsQAwwmcxkh_-HO9lFQ',
    appId: '1:290159247030:android:e9bb86d7f4fc888a9a3017',
    messagingSenderId: '290159247030',
    projectId: 'fruitmobile-31368',
    storageBucket: 'fruitmobile-31368.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyALtXTAhKnJM5HmZ84aiIdnMCBBW-Iu2Z0',
    appId: '1:290159247030:ios:828f96edf6e793369a3017',
    messagingSenderId: '290159247030',
    projectId: 'fruitmobile-31368',
    storageBucket: 'fruitmobile-31368.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyALtXTAhKnJM5HmZ84aiIdnMCBBW-Iu2Z0',
    appId: '1:290159247030:ios:828f96edf6e793369a3017',
    messagingSenderId: '290159247030',
    projectId: 'fruitmobile-31368',
    storageBucket: 'fruitmobile-31368.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication6',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDoGstM2rQaEB0fl4Qfzh0OCVtuNs3Uuh8',
    appId: '1:290159247030:web:4ddfd2c20a714cfa9a3017',
    messagingSenderId: '290159247030',
    projectId: 'fruitmobile-31368',
    authDomain: 'fruitmobile-31368.firebaseapp.com',
    storageBucket: 'fruitmobile-31368.firebasestorage.app',
  );
}
